export const typeColors: { [key: string]: string } = {
  grass: "#BFDFB3",
  poison: "#D7C8DE",
  fire: "#F4B1AE",
  electric: "#FFE69C",
  flying: "#becce9",
  water: "#bbdde7",
  bug: "#ffd0d4",
  normal: "#dee7ba",
  ground: "goldenrod",
  fairy: "violet",
  fighting: "tomato",
  psychic: "aliceblue",
  rock: "lightgray",
  steel: "steelblue",
  ice: "cornflowerblue",
  dragon: "lightgreen",
  dark: "darkgray",
  ghost: "lightyellow",
};
